name: Rebrickable.Generator Build

on:
  push:
    paths:
      - 'src/Rebrickable/Rebrickable.Generator/**'
      - '.github/workflows/rebrickable_generator_build.yml'
  schedule:
      - cron : "0 0 1 * *"
      
concurrency: 
  group: ${GITHUB_REF#refs/heads/} 
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Rebrickable/Rebrickable.Generator/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Rebrickable.Generator.csproj -r linux-x64
    - name: Build
      run: dotnet build Rebrickable.Generator.csproj -c Release -r linux-x64 --no-restore --self-contained false
    - name: Publish
      run: dotnet publish Rebrickable.Generator.csproj --no-build -c Release -o release -r linux-x64 -p:PublishSingleFile=true --self-contained false
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: RebrickableGeneratorExecutable
        path: /home/runner/work/Rebrickable/Rebrickable/src/Rebrickable/Rebrickable.Generator/release/
        retention-days: 33
      
