name: Update Rebrickable Client

on:
  push:
    paths: ".github/workflows/update_rebrickable_client.yml"
  schedule:
    - cron: "0 1 * * SUN"

env:
  REBRICKABLE_API_URL: "https://rebrickable.com/api/v3/swagger/?format=openapi"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Download settings
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: update_rebrickable_client.yml
          workflow_conclusion: success
          
      - name: Update Executable Permissions
        run: | 
        
               if [[ -f ./settings.json ]]
               then
                    echo 'SETTINGS_JSON<<EOF' >> $GITHUB_ENV
                    cat ./settings.json >> $GITHUB_ENV
                    echo 'EOF' >> $GITHUB_ENV
               fi
               
               if [ -z "$SETTINGS_JSON" ]
               then
                    echo "SCHEMA_HASH=$(echo '0' )" >> $GITHUB_ENV
                    echo "NUGET_VERSION=$(echo 0 )" >> $GITHUB_ENV
               else
                    echo "SCHEMA_HASH=$(echo $SETTINGS_JSON | jq -r '.schemaHash' )" >> $GITHUB_ENV
                    echo "NUGET_VERSION=$(echo $SETTINGS_JSON | jq -r '.nugetVersion' )" >> $GITHUB_ENV
               fi
               
      - name: Test Varaibles
        run : |
              echo $SCHEMA_HASH
              echo $NUGET_VERSION
               
  check:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      schema_new_hash: ${{ steps.schema_new.outputs.hash }}
      schema_old_hash: ${{ steps.schema_old.outputs.hash }}
    steps:
      - name: Event
        run: echo '${{ toJSON(github) }}'

      - name: Download a file
        run: curl $REBRICKABLE_API_URL -o rebrickable_schema.json

      - name: Set current schema hash
        id: schema_new
        run: echo "::set-output name=hash::$(sha256sum  rebrickable_schema.json | awk '{print $1}')"

      - name: Set current schema hash
        id: schema_old
        run: echo "::set-output name=hash::${{ env.SCHEMA_HASH }}"

  generate:
    if: ${{ needs.check.outputs.schema_new_hash != needs.check.outputs.schema_old_hash }}
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Download runner
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: rebrickable_generator_build.yml
          workflow_conclusion: success

      - name: Update Executable Permissions
        working-directory: ./RebrickableGeneratorExecutable
        run: chmod 777 Rebrickable.Generator

      - name: Update Client File
        run: |
          ./RebrickableGeneratorExecutable/Rebrickable.Generator ${{ env.REBRICKABLE_API_URL }} >> ./RebrickableGeneratorExecutable/RebrickableApiClient.cs

      - name: Upload Client File Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: RebrickableApiClient
          path: ./RebrickableGeneratorExecutable/RebrickableApiClient.cs
          retention-days: 5

  commit:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - uses: actions/checkout@v2

      - name: Download RebrickableApiClient Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: RebrickableApiClient
      
      - name: Copy Client
        run: mv ./RebrickableApiClient.cs ./src/Rebrickable/Rebrickable.Api/

      - name: Commit New Client
        uses: EndBug/add-and-commit@v9.0.0
        with:
          author_name: "Automation"
          message: "New Client File"
  publish:
    runs-on: ubuntu-latest
    #if : false
    needs : commit
    defaults:
      run:
        working-directory: ./src/Rebrickable/Rebrickable.Api/
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Rebrickable.Api.csproj
      - name: Build
        run: dotnet build Rebrickable.Api.csproj -c Release --no-restore
      - name: Pack
        run: dotnet pack Rebrickable.Api.csproj -p:PackageVersion=0.0.${{ env.NUGET_VERSION }} --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Push to Nuget
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
  post-setup:
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: update version
          run: echo "NUGET_VERSION=$(echo $NUGET_VERSION + 1)" >> $GITHUB_ENV
        
        
  
    



