name: Update Rebrickable Client

on:
  push:
    paths: ".github/workflows/update_rebrickable_client.yml"
  schedule:
  - cron : "0 1 * * SUN"

env:
  REBRICKABLE_API_URL : "https://rebrickable.com/api/v3/swagger/?format=openapi"
  SCHEMA_HASH : "X"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
     schema_new_hash: ${{ steps.schema_new.outputs.hash }}
     schema_old_hash: ${{ steps.schema_old.outputs.hash }}
    steps:
    - name: Event
      run: echo '${{ toJSON(github) }}'
      
    - name: Download a file
      run: curl $REBRICKABLE_API_URL -o rebrickable_schema.json
      
    - name: Set current schema hash
      id: schema_new
      run: echo "::set-output name=hash::$(sha256sum  rebrickable_schema.json | awk '{print $1}')"
      
    - name: Set current schema hash
      id: schema_old
      run: echo "::set-output name=hash::${{ env.SCHEMA_HASH }}"
    
  generator:
    if: ${{ needs.check.outputs.schema_new_hash != needs.check.outputs.schema_old_hash }}
    runs-on: ubuntu-latest 
    steps:
    - name: echo
      run: echo ${{ needs.check.outputs.schema_new_hash }} | echo ${{ needs.check.outputs.schema_old_hash }}
    - name: Download runner2
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: rebrickable_generator_build.yml
        workflow_conclusion: success
        
    - name: Update Executable Permissions
      working-directory: ./RebrickableGeneratorExecutable
      run: chmod 777 Rebrickable.Generator
      
    
  
      
