name: Rebrickable.Api Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Rebrickable/Rebrickable.Api/**'
concurrency: 
  group: ${GITHUB_REF#refs/heads/} 
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Rebrickable/Rebrickable.Api/
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Rebrickable.Api.csproj
      - name: Build
        run: dotnet build Rebrickable.Api.csproj -c Release --no-restore
      - name: Pack
        run: dotnet pack Rebrickable.Api.csproj -p:NuspecFile=Rebrickable.Api.nuspec --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Push to Nuget
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
      
                 
      
