name: Update Rebrickable Client

on:
  push:
    paths: ".github/workflows/update_rebrickable_client.yml"
  schedule:
  - cron : "0 1 * * SUN"

env:
  REBRICKABLE_API_URL : "https://rebrickable.com/api/v3/swagger/?format=openapi"

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: Event
      run: echo '${{ toJSON(github) }}'
      
    - name: Download a file
      run: curl $REBRICKABLE_API_URL -o rebrickable_schema.json
      
    - name: Hash PR name2
      run: sha256sum  rebrickable_schema.json

      
    
  
      
